### PR TITLE
Read CABAL_CONFIG envvar (which cabal-install reads as well)

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
I have no idea why haddock fails on travis. Have someone seen such error before?

**Comment by snoyberg** [comment]
I've essentially given up on Haddocks ever succeeding on CI, and I've been disabling them on my projects as a result. I'm 👍 on this change, would you be OK with adjusting the scripts to not build Haddock and merging when it passes?

**Comment by phadej** [comment]
Will do

**Comment by phadej** [comment]
CI green, merging...

**Pull request merged**
